apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: saas-api
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: saas-api
  endpoints:
  - port: http
    path: /metrics
    interval: 15s